---
- name: Install lazy packages
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
      - squid
      - httpd
      - python-pulp-streamer

- name: Install squid proxy configuration
  copy: src=squid.conf dest=/etc/squid/squid.conf
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 6

- name: Install squid-3.1 proxy configuration
  copy: src=squid-3.1.conf dest=/etc/squid/squid.conf
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- file: path=/var/spool/squid state=directory owner=squid group=squid mode=750

- name: Start and enable Squid service
  service: name=squid state=started enabled=yes

- name: Start and enable Pulp streamer service
  service: name=pulp_streamer state=started enabled=yes
