---

- hosts: all
  roles:
    - role: subscription-manager
      when: ansible_distribution == 'RedHat'
    - role: pulp
    - role: lazy
      when: pulp_version | version_compare('2.8', '>=')
    - role: pulp-certs
    - role: pulp-crane
