koji-target-prefix: pulp-2.15
rsync-target-dir: 2.15/stage
rsync-tested-dir: 2.15/dev
repositories:
  - name: pulp
    external_deps: deps/external_deps.json
    git_url: git@github.com:pulp/pulp.git
    git_branch: 2-master
    version: 2.15.0-0.1.alpha
  - name: pulp_puppet
    git_url: git@github.com:pulp/pulp_puppet.git
    git_branch: 2-master
    version: 2.15.0-0.1.alpha
  - name: pulp_rpm
    git_url: git@github.com:pulp/pulp_rpm.git
    git_branch: 2-master
    version: 2.15.0-0.1.alpha
  - name: pulp_docker
    git_url: git@github.com:pulp/pulp_docker.git
    git_branch: 2-master
    version: 3.1.0-0.1.alpha
  - name: crane
    git_url: git@github.com:pulp/crane.git
    git_branch: master
    version: 3.1.0-0.1.alpha
  - name: pulp_ostree
    git_url: git@github.com:pulp/pulp_ostree.git
    git_branch: 2-master
    version: 1.4.0-0.1.alpha
  - name: pulp_python
    git_url: git@github.com:pulp/pulp_python.git
    git_branch: 2-master
    version: 2.1.0-0.1.alpha
  - name: pulp_deb
    git_url: git@github.com:pulp/pulp_deb.git
    git_branch: master
    version: 1.6.0-0.1.alpha
