koji-target-prefix: pulp-2.13
rsync-target-dir: 2.13/stage
rsync-tested-dir: 2.13/dev
repositories:
  - name: pulp
    external_deps: deps/external_deps.json
    git_url: git@github.com:pulp/pulp.git
    git_branch: 2.13-dev
    version: 2.13.5-0.1.alpha
  - name: pulp_puppet
    git_url: git@github.com:pulp/pulp_puppet.git
    git_branch: 2.13-dev
    version: 2.13.5-0.1.alpha
  - name: pulp_rpm
    git_url: git@github.com:pulp/pulp_rpm.git
    git_branch: 2.13-dev
    version: 2.13.5-0.1.alpha
  - name: pulp_docker
    git_url: git@github.com:pulp/pulp_docker.git
    git_branch: 2.4-dev
    version: 2.4.1-0.1.alpha
  - name: crane
    git_url: git@github.com:pulp/crane.git
    git_branch: 2.1-dev
    version: 2.1.1-0.1.alpha
  - name: pulp_ostree
    git_url: git@github.com:pulp/pulp_ostree.git
    git_branch: 1.2-dev
    version: 1.2.2-0.1.alpha
  - name: pulp_python
    git_url: git@github.com:pulp/pulp_python.git
    git_branch: 2.0-dev
    version: 2.0.1-0.1.alpha
