repositories:
  - name: pulp
    git_url: git@github.com:pulp/pulp.git
    git_branch: 2.16-release
    version: 2.16.0-0.1.beta
  - name: pulp_puppet
    git_url: git@github.com:pulp/pulp_puppet.git
    git_branch: 2.16-release
    version: 2.16.0-0.1.beta
  - name: pulp_rpm
    git_url: git@github.com:pulp/pulp_rpm.git
    git_branch: 2.16-release
    version: 2.16.0-0.1.beta
  - name: pulp_docker
    git_url: git@github.com:pulp/pulp_docker.git
    git_branch: 3.1-release
    version: 3.1.2-0.1.beta
  - name: crane
    git_url: git@github.com:pulp/crane.git
    git_branch: 3.2-release
    version: 3.2.0-0.2.beta
  - name: pulp_ostree
    git_url: git@github.com:pulp/pulp_ostree.git
    git_branch: 1.3-release
    version: 1.3.0-1
  - name: pulp_python
    git_url: git@github.com:pulp/pulp_python.git
    git_branch: 2.0-release
    version: 2.0.2-1
  - name: pulp_deb
    git_url: git@github.com:pulp/pulp_deb.git
    git_branch: 1.7-release
    versoin: 1.7.0-0.1.beta
